services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: dra2db
      POSTGRES_USER: dra2user
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local
